### ISSUE TITLE
How to activate debugger

### ISSUE THREAD

**Issue by mankeli** [theblacklotus/quaesar#22]
Hi! Just heard about this project and gave it a go on my Linux machine and it compiled and booted 1.3 just fine! Very nice that you are doing this.

So it seems that there's atleast some remnants of the existing UAE debugger left, and I'm wondering if it's possible to activate it somehow? Or is it just not implemented at all yet?

**Comment by emoon** [comment]
Hey, Thanks!

Yeah, so I'm currently working on a UI debugger for this (that is cross-platform) but in the main while you can add these lines https://github.com/theblacklotus/quaesar/blob/dehunk/src/dummy.cpp#L988-L991

in your local code and then you will be able to press `d` to enter a commandline debugger. It's not the best, but better than nothing :)

**Comment by emoon** [comment]
Sorry, I see now it requires a bit more changes

https://github.com/theblacklotus/quaesar/commit/d4ddb42352591492b2ad3b6453135d5ff1549349
https://github.com/theblacklotus/quaesar/commit/819e803f777b03bde7f8742e012a4382960fcae0

I can try to get these integrated into the main branch, but you should be able to cherry pick these into your own local repo, but I hope I can get it done later today, but I can't promise anything

**Comment by emoon** [comment]
Hey, I have pushed these two changes to the `main` branch now so you should be able to just pull it.
